# config.yaml

#Target dir
location: "/data/2025-10-10_EXP10-10"

#sample prep
prep:
  nsample: 500

#Runs to analyze
samples:
  - Chip1

#Alignment parameters
alignment:
  cutoff: 0.90
  reference: "Inputs/Target.fasta"
  umi_tools_fwd: "Scripts/umi_tools_fwd.sh"
  umi_tools_rev: "Scripts/umi_tools_rev.sh"
  grab_umi: "Scripts/grab_umi.py"
  umi_filter: "Scripts/umi_strict_filter.py"
